using System.ComponentModel.DataAnnotations;
using ReactLiveSoldProject.ServerBL.Base;
using ReactLiveSoldProject.ServerBL.Models.Authentication;
using ReactLiveSoldProject.ServerBL.Models.Sales;

namespace ReactLiveSoldProject.ServerBL.Models.CustomerWallet
{
    public class WalletTransaction
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "El ID de la organización es obligatorio")]
        public Guid OrganizationId { get; set; }

        public virtual Organization Organization { get; set; }

        [MaxLength(50, ErrorMessage = "El número de transacción no puede exceder los 50 caracteres")]
        public string? TransactionNo { get; set; } // WT-2025-0001

        [Required(ErrorMessage = "El ID de la billetera es obligatorio")]
        public Guid WalletId { get; set; }

        public virtual Wallet Wallet { get; set; }

        [Required(ErrorMessage = "El tipo de transacción es obligatorio")]
        public TransactionType Type { get; set; }

        [Required(ErrorMessage = "El monto es obligatorio")]
        [Range(0.01, double.MaxValue, ErrorMessage = "El monto debe ser mayor a 0")]
        public decimal Amount { get; set; }

        public Guid? RelatedSalesOrderId { get; set; }

        public virtual SalesOrder? RelatedSalesOrder { get; set; }

        // This transaction might be generated by a receipt
        public Guid? ReceiptId { get; set; }
        public virtual Receipt? Receipt { get; set; }

        public Guid? AuthorizedByUserId { get; set; }

        public virtual User? AuthorizedByUser { get; set; }

        [MaxLength(1000, ErrorMessage = "Las notas no pueden exceder los 1000 caracteres")]
        public string? Notes { get; set; }

        /// <summary>
        /// Indica si la transacción ha sido posteada (afecta el balance del wallet)
        /// Las transacciones se crean como borrador (IsPosted = false) y deben ser autorizadas
        /// </summary>
        public bool IsPosted { get; set; } = false;

        /// <summary>
        /// Balance del wallet ANTES de aplicar esta transacción
        /// Solo se completa cuando IsPosted = true
        /// </summary>
        public decimal? BalanceBefore { get; set; }

        /// <summary>
        /// Balance del wallet DESPUÉS de aplicar esta transacción
        /// Solo se completa cuando IsPosted = true
        /// </summary>
        public decimal? BalanceAfter { get; set; }

        /// <summary>
        /// Usuario que posteó la transacción
        /// </summary>
        public Guid? PostedByUserId { get; set; }

        public virtual User? PostedByUser { get; set; }

        /// <summary>
        /// Fecha en que se posteó la transacción
        /// </summary>
        public DateTime? PostedAt { get; set; }

        [MaxLength(500)]
        public string? Reference { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}
